################################################################
# API and dashboard configuration
################################################################
api:
  # Dashboard
  #
  #
  dashboard: true
  insecure: true
################################################################
# Docker configuration backend
################################################################
providers:
  docker:
    exposedByDefault: false
################################################################
# Traefik Logging
################################################################
log:
  level: INFO

################################################################
# Entrypoint
################################################################
entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

################################################################
# Challenege DNS
################################################################
certificatesResolvers:
  myresolver:
    acme:
      email: sid@tamu.edu 
      storage: acme.json
      dnsChallenge:
        provider: manual
        delayBeforeCheck: 0
